version: 2
jobs:
  build:
    working_directory: /go/src/github.com/VividCortex/mysql
    docker:
      - image: circleci/golang:1.13.3
    environment:
      MYSQL_TEST_DBNAME: circle_test
    steps:
      - checkout
      - run: go test -race ./...
